description = "Base builder for drycc stack, based on debian base image"

[lifecycle]
version = "{LIFECYCLE_VERSION}"

[[buildpacks]]
  id = "drycc/ruby"
  version = "0.0.1"
  uri = "./buildpacks/ruby"

[[order]]
[[order.group]]
id = "drycc/ruby"
version = "0.0.1"

[[buildpacks]]
  id = "drycc/python"
  version = "0.0.1"
  uri = "./buildpacks/python"

[[order]]
[[order.group]]
id = "drycc/python"
version = "0.0.1"

[[buildpacks]]
  id = "drycc/go"
  version = "0.0.1"
  uri = "./buildpacks/go"

[[order]]
[[order.group]]
id = "drycc/go"
version = "0.0.1"


[[buildpacks]]
  id = "drycc/node"
  version = "0.0.1"
  uri = "./buildpacks/node"

[[order]]
[[order.group]]
id = "drycc/node"
version = "0.0.1"


[[buildpacks]]
  id = "drycc/rust"
  version = "0.0.1"
  uri = "./buildpacks/rust"

[[order]]
[[order.group]]
id = "drycc/rust"
version = "0.0.1"

[[buildpacks]]
  id = "drycc/java"
  version = "0.0.1"
  uri = "./buildpacks/java"

[[order]]
[[order.group]]
id = "drycc/java"
version = "0.0.1"

[[buildpacks]]
  id = "drycc/php"
  version = "0.0.1"
  uri = "./buildpacks/php"

[[order]]
[[order.group]]
id = "drycc/php"
version = "0.0.1"

[stack]
id = "{STACK_ID}"
run-image = "{STACK_RUN_IMAGE}"
build-image = "{STACK_BUILD_IMAGE}"
