ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG STACK_ID

ARG DRYCC_UID=1001
ARG DRYCC_GID=1001
ARG DRYCC_HOME_DIR=/workspace

RUN groupadd drycc --gid ${DRYCC_GID} \
  && useradd drycc -u ${DRYCC_UID} -g ${DRYCC_GID} -s /bin/bash -m -d ${DRYCC_HOME_DIR} \
  && chown drycc:drycc /opt

USER drycc

ENV CNB_USER_ID ${DRYCC_UID}
ENV CNB_GROUP_ID ${DRYCC_GID}
ENV CNB_STACK_ID ${STACK_ID}
ENV CNB_APP_DIR ${DRYCC_HOME_DIR}
ENV HOME ${DRYCC_HOME_DIR}

LABEL io.buildpacks.stack.id="${STACK_ID}"


