ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG pack_uid=1000
ARG pack_gid=1000

RUN ln -s /workspace /app \
  && groupadd drycc --gid ${pack_gid} \
  && useradd drycc -u ${pack_uid} -g ${pack_gid} -s /bin/bash -m \
  && chown -R drycc:drycc /usr/sbin/nginx /var/log/nginx

ARG STACK
LABEL io.buildpacks.stack.id="${STACK}"
USER drycc
ENV HOME /app
