ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root
RUN cp -rf /var/lib/dpkg /var/lib/dpkg-run; \
  \
  \
  install-packages zlib1g git autoconf pkg-config build-essential; \
  install-stack jq 1.6; \
  install-stack yj 5.0.0; \
  cp -rf /opt/drycc/*/bin/* /usr/local/bin; \
  rm -rf /opt/drycc/*; \
  \
  \
  rm -rf /var/lib/dpkg; \
  mv /var/lib/dpkg-run /var/lib/dpkg;
ADD rootfs /

USER ${DRYCC_UID}