# Buildpack API version
api = "0.7"

# Buildpack ID and metadata
[buildpack]
id = "drycc/go"
version = "0.0.1"
name = "Go Buildpack"
homepage = "https://github.com/drycc/pack-images/tree/main/buildpacks/go"

# Stacks that the buildpack will work with
[[stacks]]
id = "drycc-bullseye"
