matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  type: exec
  platform: ${platform}

steps:
- name: publish-linux
  image: bash
  commands:
  - echo $CONTAINER_PASSWORD | podman login $DRYCC_REGISTRY --username $CONTAINER_USERNAME --password-stdin > /dev/null 2>&1
  - sed -i "s/registry.drycc.cc/$${DRYCC_REGISTRY}/g" builder.toml
  - sed -i "s/{{CODENAME}}/$${CODENAME}/g" builder.toml
  - export PACK_HOME=$CI_WORKSPACE
  - make publish-buildpack
  secrets:
  - codename
  - dev_registry
  - drycc_registry
  - container_username
  - container_password
  when:
    event:
    - push
    - tag

depends_on:
- test-linux
- manifest-pack
