labels:
  type: exec
  platform: linux/amd64

steps:
- name: generate-manifest
  image: bash
  commands:
  - sed -i "s/registry.drycc.cc/$${DRYCC_REGISTRY}/g" .woodpecker/manifest-buildpacks.tmpl
  - sed -i "s/{{codename}}/$${CODENAME}/g" .woodpecker/manifest-buildpacks.tmpl
  environment:
    CODENAME:
      from_secret: codename
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    CONTAINER_USERNAME:
      from_secret: container_username
    CONTAINER_PASSWORD:
      from_secret: container_password
  when:
    event:
    - push
    - tag
    - cron

- name: publish-buildpacks-image
  image: bash
  commands:
  - podman run --rm
    -e PLUGIN_SPEC=.woodpecker/manifest-buildpacks.tmpl
    -e PLUGIN_USERNAME=$CONTAINER_USERNAME
    -e PLUGIN_PASSWORD=$CONTAINER_PASSWORD
    -e DRONE_TAG=$CI_COMMIT_TAG
    -v $(pwd):$(pwd)
    -w $(pwd)
    plugins/manifest
  environment:
    CONTAINER_USERNAME:
      from_secret: container_username
    CONTAINER_PASSWORD:
      from_secret: container_password
  when:
    event:
    - push
    - tag
    - cron

depends_on:
- build-linux-buildpacks
