matrix:
  platform:
  - linux/amd64
  - linux/arm64

platform: ${platform}

labels:
  type: exec

pipeline:
- name: test-linux
  image: bash
  commands:
  - CODENAME=$${CODENAME} make test-style
  environment:
    CODENAME: bullseye
  secrets:
  - dev_registry
  - codecov_token
  - drycc_registry
  when:
    event:
    - push
    - tag
    - pull_request
