#!/usr/bin/env bash
layers_dir=$1

gradle_layer_dir="${layers_dir}/gradle"

if [[ ! -d ${gradle_layer_dir} ]]; then
  mkdir -p ${gradle_layer_dir}
  cat > "${gradle_layer_dir}.toml" << EOF
[types]
cache = true
EOF
fi
ln -s ${gradle_layer_dir} $HOME/.gradle

# 5. RUN BUILD
echo "---> Running Gradle Wrapper"
./gradlew clean build -x test --no-daemon


