#!/usr/bin/env bash
layers_dir=$1
target_layer_dir=$2
maven_layer_dir="${layers_dir}/maven"
mkdir -p "${maven_layer_dir}"
# maven build
echo "---> Building target with maven"
cp -rf "$(pwd)" /tmp/source \
  && cd /tmp/source \
  && ln -s "${layers_dir}/maven" "${HOME}/.m2" \
  && bash mvnw clean install -B -DskipTests \
  && mv /tmp/source/target "${target_layer_dir}" \
  && cd -

cat >"${target_layer_dir}/profile.d/target.sh" <<EOL
# only execute at runtime
if [ -z "\$INIT_STACK" ]; then
  rm -rf $(pwd)/target
  cp -rf ${target_layer_dir}/target $(pwd)
fi
EOL

cat >"${maven_layer_dir}.toml" <<EOL
[types]
cache = true
build = true
launch = false
EOL
